KUET_Rent_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mess.urls', 'mess'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mess/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home_view, mess_details_view, space_details_view

app_name = "mess"
urlpatterns = [
    path('', home_view, name='home'),
    path('<mess_name>/', mess_details_view, name="mess_details"),
    path('<mess_name>/<space_name>/', space_details_view, name="space_details")
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager, PermissionsMixin, Permission
from django.conf import settings


class MyAccountManager(BaseUserManager):

    def create_user(self,email,username,password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not username:
            raise ValueError("User must have an username address")

        user=self.model(
            email=self.normalize_email(email),
            username=username
            )
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self,email,username,password):
        user=self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            )
        user.is_admin=True
        user.is_staff=True
        user.is_superuser=True
        user.save(using=self._db)
        return user


def profile_picture_location(instance, filename):
    file_path = 'pp/{filename}'.format(
            filename = filename
        )
    return file_path
    
class Account(AbstractBaseUser, PermissionsMixin):
    email						= models.EmailField(verbose_name="email",max_length=61,unique=True)
    username					= models.CharField(max_length=31)
    phone_number                = models.CharField(max_length=15, unique=True, null=True, blank=True)
    profile_picture				= models.ImageField(upload_to=profile_picture_location, null=True, blank=True)
    is_owner					= models.BooleanField(default=False)

    date_joined					= models.DateTimeField(verbose_name="date_joined",auto_now_add=True)
    last_login					= models.DateTimeField(verbose_name="last_login",auto_now=True)
    is_admin					= models.BooleanField(default=False)
    is_active					= models.BooleanField(default=True)
    is_staff					= models.BooleanField(default=False)
    is_superuser				= models.BooleanField(default=False)

    
    USERNAME_FIELD ='email'
    REQUIRED_FIELDS =["username",]

    objects = MyAccountManager()


    def __str__(self):
        return self.email +', '+self.username

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_level):
        return True

    # def get_user_permissions(self, obj=None):
    #     return user.user_permissions.all()

    # def get_all_permissions(self, obj=None):
    #     return Permission.objects.all()

    # def get_user_permissions(user):
    #     if user.is_superuser:
    #         return Permission.objects.all()
    #     return user.user_permissions.all() | Permission.objects.filter(group__user=user)

    

mess/models.py
from django.db import models

from account.models import Account

def mess_picture_location(instance, filename):
    file_path = 'mess/{mess_name}/{filename}'.format(
            filename = filename,
            mess_name = instance.name
        )
    return file_path

def mess_space_picture_location(instance, filename):
    file_path = 'mess/{mess_name}/{space_name}/{filename}'.format(
            filename = filename,
            mess_name = instance.name,
            space_name = instance.name
        )
    return file_path

class Category(models.Model):
    name                     = models.CharField(max_length=15, unique=True)


    def __str__(self):
        return self.name
    



class Mess(models.Model):
    name                    = models.CharField(max_length=31, unique=True)
    category                = models.ForeignKey(Category, on_delete=models.CASCADE)
    owner                   = models.ForeignKey(Account, on_delete=models.CASCADE)
    distance                = models.IntegerField()
    price_range             = models.CharField(max_length=15)
    image_1                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)
    details                 = models.TextField(max_length=501)

    def __str__(self):
        return self.name




class Space(models.Model):
    image_1                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)
    image_2                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)
    image_3                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)
    image_4                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)
    image_5                 = models.ImageField(upload_to=mess_picture_location, null=True, blank=True)

    mess                    = models.ForeignKey(Mess, on_delete=models.CASCADE)
    name                    = models.CharField(max_length=31, unique=True)
    details                 = models.TextField(max_length=501)
    price                   = models.IntegerField()
    mess_type               = models.CharField(max_length=15)
    square_fit              = models.IntegerField()

    
    total_room              = models.IntegerField(default=1)
    washroom                = models.IntegerField(default=1)
    is_attach_washroom      = models.BooleanField(default=False)
    kitchen                 = models.BooleanField(default=False)
    corridor                = models.BooleanField(default=False)
    total_windows           = models.IntegerField(default=1)
    

    room_capability         = models.IntegerField(default=1)

    def __str__(self):
        return self.name
    

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from account.models import Account


class RegistrationForm(UserCreationForm):
	email=forms.EmailField(max_length=61,help_text="Required. Add a vaild email Address")



	class Meta:
		model=Account
		fields=('email','username','password1','password2')



class AccountAuthenticationForm(forms.ModelForm):

	password= forms.CharField(label="password",widget=forms.PasswordInput)


	class Meta:
		model=Account
		fields=('email','password')


	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email,password=password):
				raise forms.ValidationError("Invalid Login")



class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email','username', 'profile_picture')

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email

		raise forms.ValidationError('Email "%s" is already used.'%email)



	def clean_username(self):
		username= self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username

		raise forms.ValidationError('User Name "%s" is already used.'%username)

account/views.py
from django.shortcuts import render

# Create your views here.

mess/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .models import Category, Mess, Space

def home_view(request):
    context = {}
    messes = Mess.objects.all()
    print(messes)
    context['messes'] = messes
    return render(request, 'home.html', context)


def mess_details_view(request, mess_name):
    context = {}
    print(mess_name)
    mess_details = Space.objects.filter(mess__name=mess_name)
    print(mess_details)
    context['spaces'] = mess_details
    return render(request, "mess_details.html", context)



def space_details_view(request, mess_name, space_name):
    context = {}
    print(mess_name)
    print(space_name)
    space_details = Space.objects.filter(mess__name=mess_name, name=space_name)[0]
    # space_details = Space.objects.filter(mess__name = "White House", name =  "W_H 1A")[0]
    print(space_details.mess_type)
    context["space"] = space_details
    return render(request, "spece_details.html", context)

mess/templates/home.html
{% extends 'base.html' %}


{% block title %}Listing | {% endblock %}

{% block content %}

  <!-- Showcase -->
  <section class="py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Property Listing</h1>
        </div>
      </div>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        {% if messes %}
          {% for mess in messes %}
            <div class="col-md-4 mb-4">
              <div class="card listing-preview shadow-sm">
                {% comment %} {% thumbnail listing.photo_main "400x300" crop="100%" as photo %} {% endcomment %}
                {{mess.name}}
                  <a href="{% url 'mess:mess_details' mess.name %}">
                    <img class="card-img-top" src="{{ mess.image_1.url }}" alt="">
                    <div class="card-img-overlay">
                      <h2>
                      <span
                          class="badge bg-price text-white">${{ mess.price_range}}<span class="font-weight-normal"></span></span>
                      </h2>
                    </div>
                  </a>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <p><i
                        class="fa fa-map-marker-alt"></i> {{ listing.city }}, {{ listing.state }} {{ listing.zipcode }}
                    </p>
                  </div>
                  <hr>
                  <div class="row py-2">
                    <div class="col-6">
                      <i class="fa fa-bed"></i> {{ listing.bedrooms }} bd
                    </div>
                    <div class="col-6">
                      <i class="fa fa-bath"></i> {{ listing.bathrooms|floatformat }} ba
                    </div>
                  </div>
                  <div class="row py-2">
                    <div class="col-6">
                      <i class="fa fa-th-large"></i> {{ listing.sqft }} sqft
                    </div>
                    <div class="col-6">
                      <i class="fa fa-home"></i> {{ mess.category }}</div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-12">
            <p>No listing available</p>
          </div>
        {% endif %}
      </div>

      <!-- Pagination -->
      <div class="row mt-5">
        <div class="col-md-12">
          {% if listings.has_other_pages %}
            <ul class="pagination justify-content-center">
              {% if listings.has_previous %}
                <li class="page-item">
                  <a href="?page={{ listings.previous_page_number }}" class="page-link">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&laquo;</a>
                </li>
              {% endif %}
              {% for i in listings.paginator.page_range %}
                {% if listings.number == i %}
                  <li class="page-item active">
                    <a class="page-link">{{ i }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if listings.has_next %}
                <li class="page-item">
                  <a href="?page={{ listings.next_page_number }}" class="page-link">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

mess/templates/mess_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
    .font-slider{
        width:100%;
        {% comment %} height:50%; {% endcomment %}
    }
</style>
<div class="font-slider" style="height:501px;">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100 h-50" src="https://images.unsplash.com/photo-1580587771525-78b9dba3b914?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyMzYzMTR8MHwxfHNlYXJjaHwxfHxIb3VzZXx8MHx8fHwxNjMxODEzNTk1&ixlib=rb-1.2.1&q=80&w=1080" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100 h-50" src="https://images.unsplash.com/photo-1475855581690-80accde3ae2b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100 h-50" src="https://images.unsplash.com/photo-1554995207-c18c203602cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyMzYzMTR8MHwxfHNlYXJjaHw0fHxIb3VzZXx8MHx8fHwxNjMxODEzNjQ4&ixlib=rb-1.2.1&q=80&w=1080" alt="First slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</div>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			{% comment %} <div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'codingwithmitch_logo.png' %}" width="72" height="72">
					<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
	  					framework and you'll see why in this course.</p>
					<p class="m-auto"><a class="btn btn-primary" href="#">Create post</a></p>
				</div>
			</div> {% endcomment %}
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if spaces %}
				{% for space in spaces %}
					<div class="blog-post-container">
						{% include 'snippets/space.html' with space=space %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
						{% comment %} {% include 'blog/snippets/blog_post_snippet.html' with query=query %} {% endcomment %}
					</div>
			{% endif %}
			<!-- End Blog posts-->

			{% comment %} {% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %} {% endcomment %}
		</div>
		<!-- end blog feed -->

	</div>
</div>

{% endblock content %}

mess/templates/snippets/space.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>

{% if space %}
	<div class="container">
		<div class="row">
			<!-- Space -->
			<div class="card m-auto">
				<a href="{% url 'mess:space_details' space.mess.name space.name %}">
					<img class="card-img-top" src="{{space.image_1.url}}">
				</a>
				<div class="card-body mt-2 mb-2">
					<a href="#">
						<h2 class="card-title">{{blog_post.title}}</h2>
					</a>
					<p class="card-text">{{blog_post.body |safe| truncatechars:180}}</p>
					{% if blog_post.auther == request.user %}
						<a href="#" class="btn btn-primary">Update</a>
					{% endif %}
				</div>
				<div class="card-footer text-muted">
				  Updated on {{blog_post.date_updated}} by {{blog_post.author}}
				</div>
			</div>
		</div>
	</div>

{% else %}

	<div class="container">
		<div class="row">
			<div class="card m-auto">
				<div class="card-body mt-2 mb-2">
					<h2 class="card-title">No results</h2>
					<p class="card-text">There were no results matching the search: "{{query}}"</p>
				</div>
			</div>
		</div>
</div>

{% endif %}

mess/templates/spece_details.html
{% extends 'base.html' %}

{% block title %}{{ space.name }} | {% endblock %}

{% load thumbnail %}

{% block content %}

  <!-- Showcase -->
  <section class="py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{ space.name }}</h1>
        </div>
      </div>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <div class="row">
        <!-- Images -->
        <div class="col-md-7">
          <div class="container">
            <div class="row">
              <div class="px-1 shadow-sm">
                {% if space.image_1 %}
                {% thumbnail space.image_1 "1200x900" crop="100%" as photo %}
                    <a href="{{ space.image_1.url }}" data-toggle="lightbox" data-gallery="gallery">
                      <img src="{{ space.image_1.url }}">
                    </a>
                {% endthumbnail %}
                {% endif %}
              </div>
            </div>
            <div class="row mt-1">
              <div class="col-3 px-1">
                {% if space.image_2 %}
                    <a href="{{ space.image_2.url }}" data-toggle="lightbox" data-gallery="gallery">
                      <img src="{{ space.image_2.url }}">
                    </a>
                {% endif %}
              </div>
              <div class="col-3 px-1">
                {% if space.image_3 %}
                    <a href="{{ space.image_3.url }}" data-toggle="lightbox" data-gallery="gallery">
                      <img src="{{ space.image_3.url }}">
                    </a>
                {% endif %}
              </div>
              <div class="col-3 px-1">
                {% if space.image_4 %}
                    <a href="{{ space.image_4.url }}" data-toggle="lightbox" data-gallery="gallery">
                      <img src="{{ space.image_4.url }}">
                    </a>
                {% endif %}
              </div>
              <div class="col-3 px-1">
                {% if space.image_5 %}
                    <a href="{{ space.image_5.url }}" data-toggle="lightbox" data-gallery="gallery">
                      <img src="{{ space.image_5.url }}">
                    </a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>

        <!-- Text -->
        <div class="col-md-5">
          <div class="container">
            <div class="row">
              <h2><span class="h1">${{ space.price }}</span>/</h2>
            </div>
            <div class="row mt-4 font-italic">
              <p>{{ space.total_room }}  </p>
            </div>
            <div class="row mt-1 font-italic">
            adress
            </div>
            <div class="row mt-1 font-italic badge badge-danger">
              <div class="text-light">{{ space.mess_type }}</div>
            </div>
            <hr class="mt-4">
            <div class="row mt-4">
              <div>{{ space.details }}</div>
            </div>
            <hr class="mt-3">
            <div class="row mt-5">
              <div class="col-9 mx-auto">
                <button class="btn btn-outline-primary btn-block shadow-sm" data-toggle="modal"
                        data-target="#inquiryModal"></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Contact Modal -->
  <section>
    <div class="modal fade" id="inquiryModal" role="dialog">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="inquiryModalLabel"></h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% comment %} <form action="#" method="POST">
              {% csrf_token %}
                <input type="hidden" name="user_id" value="{{  }}">
{#              <input type="hidden" name="realtor_email" value="{{ listing.user.email }}">#}
              <input type="hidden" name="listing_id" value="{{ space.mess }}">
              <input type="hidden" name="listing" value="{{ space.name}}">
              <div class="form-group">
                <label for="name" class="col-form-label"></label>
                <input type="text" name="name" class="form-control" {% if user.is_authenticated %}
                       value="{{  }} {{  }}" {% endif %} required>
              </div>
              <div class="form-group">
                <label for="email" class="col-form-label"></label>
                <input type="email" name="email" class="form-control" {% if user.is_authenticated %}
                       value="{{  }}" {% endif %}>
              </div>
              <div class="form-group">
                <label for="phone" class="col-form-label"></label>
                <input type="text" name="phone" class="form-control">
              </div>
              <div class="form-group">
                <label for="message" class="col-form-label"></label>
                <textarea name="message" class="form-control" rows="5" required></textarea>
              </div>
              <hr>
              <input type="submit" value="" class="btn btn-block btn-primary">
            </form> {% endcomment %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container mt-3">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
          {% else %}
            {{ message.tags | title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <!-- Lightbox -->
    <link rel="stylesheet" href="{% static 'css/ekko-lightbox.css' %}" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- Favicon -->
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'favicon_io/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'favicon_io/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'favicon_io/favicon-16x16.png' %}"
    />
    <link rel="manifest" href="{% static 'favicon_io/site.webmanifest' %}" />

    <title>{% block title %}{% endblock %}KUET Mess Rent</title>
  </head>
  <body class="bg-light">
    <!-- NavBar -->
    {% include 'navbar.html' %}

    <!-- Alert -->
    {% include 'alerts.html' %}

    <!-- Main Content -->
    {% block content %}{% endblock %}

    <!-- Footer -->
    {% include 'footer.html' %}

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/ekko-lightbox.min.js' %} "></script>
    <script src="{% static 'js/main.js' %} "></script>
  </body>
</html>

templates/footer.html
<!-- Footer -->
<footer class="footer py-5 text-center">
  <div class="container">
    <small
      >&copy; <a href="mailto: me.xinyuwen@gmail.com"> Xinyu Wen</a>. All rights reserved.
    </small>
  </div>
</footer>

templates/navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark sticky-top bg-navy">
  <div class="container">
    <a class="navbar-brand mr-5" href="{% url 'mess:home' %}">KUET Mess Rent</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li
            {% if '/en/' == request.path or '/zh-hans/' == request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
        >
          <a class="nav-link" href="{% url 'mess:home' %}">Home</a>
        </li>
        <li
            {% if 'search' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
        >
          <a class="nav-link" href="#">Search</a>
        </li>
        <li
            {% if 'listings' in request.path and 'search' not in request.path and 'upload' not in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
        >
          <a class="nav-link" href="#"></a>
        </li>
        <li
            {% if 'upload' in request.path %}
              class="nav-item active"
            {% else %}
              class="nav-item"
            {% endif %}
        >
          <a class="nav-link" href="#">Add a Listing</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown mr-3">
          <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
            {% if LANGUAGE_CODE == 'en' %}
              English
            {% else %}
              简体中文
            {% endif %}
            {% comment %}{% trans "English" %}{% endcomment %}
          </a>
        </li>

        {% if user.is_authenticated %}
          <li
              {% if 'dashboard' in request.path %}
                class="nav-item active mr-3"
              {% else %}
                class="nav-item mr-3"
              {% endif %}
          >
            <a class="nav-link" href="#">
              Dashboard</a>
          </li>
          <li class="nav-item">
            <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
              <i class="fas fa-sign-out-alt"></i>Logout
            </a>
            <form action="#" method="POST" id="logout">
              {% csrf_token %}
              <input type="hidden">
            </form>
          </li>
        {% else %}
          <li
              {% if 'register' in request.path %}
                class="nav-item active mr-3"
              {% else %}
                class="nav-item mr-3"
              {% endif %}
          >
            <a class="nav-link" href="#">
              <i class="fas fa-user-plus"></i>Register</a>
          </li>
          <li
              {% if 'login' in request.path %}
                class="nav-item active"
              {% else %}
                class="nav-item"
              {% endif %}
          >
          {% comment %} {% url 'login' %}?next={{ request.path | urlencode }} {% endcomment %}
            <a class="nav-link" href="#">
              <i class="fas fa-sign-in-alt"></i>Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>